# Travis config file to build spk package
# Adapted from https://github.com/torrentalle/spksrc/tree/gogs-build
# And https://github.com/jelmerj/spksrc

# Only build tags
if: tag IS present

env:
  global:
    - PKG=sickrage
  matrix:
    - SYNOARCH=arch-rtd1296-6.1

# Output is too verbose for TravisCI, so we hide it
# Remove the ">/dev/null" part to debug!
# make arch-$SYNOARCH always return exit code 0.
# The "ls" line is to test if SPK has been build.
script:
  - docker pull synocommunity/spksrc
  - docker run -it -v `pwd`:/spksrc synocommunity/spksrc /bin/bash -c "cd /spksrc && make setup && cd spk/$PKG && make $SYNOARCH>/dev/null"
  - ls packages/*.spk

services:
  - docker

notifications:
  email: false

git:
  depth: 1

deploy:
  provider: releases
  api_key:
    secure: gw75ikEVKQGzuYrcuusRdI+y4FpsvX1bF7yVwEGTgorDvyyF1oq/kSlJmCiO3taZkuxF+dvGpXvlkQ1MtPbpx7rr7fooRmP0xjMsrJd+nNcQII9ehAlflGcL9ToVbo9GHIlZLwrHjE/Buch1b6gbexQFeobpXR7epUAqxupigcMyyk84skuDXySTUPQ6BZrFCH7a2rnp0mI4ymzw8A0Z7CID/OzQaq/eih1+1vO7cGNz1APoBumm74MlnUiRiDgCHLNruj+upHNjmvrUJ8mocIznI7csCR/aZrLScNU5+uSq76T8Kc2FRpqigUbGPEC2Pc3AFPyB0IM/Zg8cPrn3CVzxcLFKmOysoLRF5H+d50vPNDC/afMDv6dfMrgVureEYGKov8eg9QMUnjIca20qqkDvGzJ7a/GT6zyz7txSBA4WiMDFb/EASbsEM78D9W7B3WsZ5vfxE91yUXCfQkGD/VHcFK0CYNgD1HMAutjewVhzxHkX8zYaJERpIcKKq154NiSKVOiWIUDp1JGaMe6rX69HM7HYMaHHJBBXEOvwusgIy/uCveGct/wNJzZomJVDkbtcwjOW9drnKud5U6icEwQ99HJ+vFtn+NESKM8EW2168t11KEfb48IduwdGvC/u1GLYy4vVuQdJyrnuR2hop6jyLfzNW4xMqPL32Xn7cjc=
  file_glob: true
  file: packages/*.spk
  skip_cleanup: true
  overwrite: true
  on:
    tags: true